version: '3'
services:
  frontend: 
    build: ./frontend
    container_name: frontend_container
    ports:
      - "3000:3000"
    networks:
      - app-network
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      - MONGO_URL=mongodb://mongo:27017/edukativna_platforma
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data: 
 
