version: '3'
services:
  frontend: 
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./env/frontend.env
    networks:
      - app-network
  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
    env_file:
      - ./env/backend.env
    networks:
      - app-network
  mongo:
    image: mongo
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
networks:
  app-network:
    driver: bridge
volumes:
  mongo-data: 
 
